version: "3.8"

services:
  frontend:
    container_name: app-frontend
    image: app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 85:80
    environment:
      NODE_ENV: production

  backend:
    container_name: app-backend
    image: app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  
volumes:
  mongodb_data_container: