version: "3.8"

services:
  frontend:
    container_name: app-frontend
    image: app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 85:80
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:8080
    depends_on:
      - 'mongo'

  backend:
    container_name: app-backend
    image: app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://mongo:27017/tasks
    depends_on:
      - 'mongo'

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: tasks
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  
volumes:
  mongodb_data_container: